# Student agent: Add your own agent here
#from agents.agent import Agent
import numpy as np
from Node import *
from agent import Agent
import math
import sys
#from store import register_agent



#@register_agent("my_agent")
class agentTest(Agent):
    """
    A dummy class for your implementation. Feel free to use this class to
    add any helper functionalities needed for your agent.
    """

    def __init__(self):
        super(agentTest, self).__init__()
        self.name = "testAgent"
        self.dir_map = {
            "u": 0,
            "r": 1,
            "d": 2,
            "l": 3,
        }


    def step(self, chess_board, my_pos, adv_pos, max_step):
        """
        Implement the step function of your agent here.
        You can use the following variables to access the chess board:
        - chess_board: a numpy array of shape (x_max, y_max, 4)
        - my_pos: a tuple of (x, y)
        - adv_pos: a tuple of (x, y)
        - max_step: an integer

        You should return a tuple of ((x, y), dir),
        where (x, y) is the next position of your agent and dir is the direction of the wall
        you want to put on.

        Please check the sample implementation in agents/random_agent.py or agents/human_agent.py for more details.
        """
        return my_pos, dir




    '''
    #backpropagation during each simulation

    #receive a list of Node generated by 1 simulation and a notion whether the agent wins or not
    #change the num_visited and num_wins of everynode along the path

    




    #An array of paths generated by simulations, paths is a list of tuples where (node,  a list of 2 numbers(number of visited + number of success)).

    #for each simulation, backpropagate values of nodes(visited times, number of success)

    #calculate UCTs for the direct children and find the best one

    #expand the node by returning this child
    '''
    def check_valid_step(self, chess_board, start_pos, end_pos, adv_pos, barrier_dir, step):
        """
        Check if the step the agent takes is valid (reachable and within max steps).
        Parameters
        ----------
        start_pos : tuple
            The start position of the agent.
        end_pos : np.ndarray
            The end position of the agent.
        barrier_dir : int
            The direction of the barrier.
        """
        # Endpoint already has barrier or is boarder
        moves = ((-1, 0), (0, 1), (1, 0), (0, -1))
        r, c = end_pos
        if chess_board[r, c, barrier_dir]:
            return False
        if np.array_equal(start_pos, end_pos):
            return True

        # BFS
        state_queue = [(start_pos, 0)]
        visited = {tuple(start_pos)}
        is_reached = False
        while state_queue and not is_reached:
            print("pop out?\n", state_queue[0])

            cur_pos, cur_step = state_queue.pop(0)

            print("cur_pos is:\n", cur_pos)
            print("cur_steo is:\n", cur_step)
            r, c = cur_pos
            if cur_step == step:
                break
            for dir, move in enumerate(moves):
                if chess_board[r, c, dir]:
                    continue

                next_pos = (cur_pos[0] + move[0], cur_pos[1] + move[1])
                if np.array_equal(next_pos, adv_pos) or tuple(next_pos) in visited:
                    continue
                if np.array_equal(next_pos, end_pos):
                    is_reached = True
                    break

                visited.add(tuple(next_pos))
                state_queue.append((next_pos, cur_step + 1))
                print("the queue is:\n", state_queue)

        return is_reached

    #get all actions under the root Node
    def getActions(self, rootNode, adv_pos, step, chess_board):
        #boardsize chess_board.boardsize
        x = 4
        y = 4
        my_pos = rootNode.get_pos()
        r = 0
        actions = []
        for r in range(step):
            c = step - r
            print("r is:\n", r)
            print("c is:\n", c)
            if 0<=(my_pos[0] + r)<=x-1 and 0<=(my_pos[0] - r)<=x-1 and 0<=(my_pos[1] + c)<=x-1 and 0<=(my_pos[1] - c)<=x-1: #3 is the size of the chessboard
                next_pos = (my_pos[0] + r, my_pos[1] + c)
                print("pos1",next_pos)
                next_pos2 = (my_pos[0] - r, my_pos[1] + c)
                print("pos2",next_pos2)
                next_pos3 = (my_pos[0] + r, my_pos[1] - c)
                print("pos3",next_pos3)
                next_pos4 = (my_pos[0] - r, my_pos[1] - c)
                print("pos4",next_pos4)
                for i in range(4):
                    if (self.check_valid_step(chess_board, my_pos, next_pos, adv_pos, i, step)):
                        n1 = Node(next_pos, i, parent = my_pos)
                        n1.parent = rootNode
                        actions.append(n1)
                    if (self.check_valid_step(chess_board, my_pos, next_pos2, adv_pos,i,step)):
                        n2 = Node(next_pos2, i, parent=my_pos)
                        n2.parent = rootNode
                        actions.append(n2)
                    if (self.check_valid_step(chess_board, my_pos, next_pos3, adv_pos,i,step)):
                        n3 = Node(next_pos3, i, parent=my_pos)
                        n3.parent = rootNode
                        actions.append(n3)
                    if (self.check_valid_step(chess_board, my_pos, next_pos4, adv_pos,i,step)):
                        n4 = Node(next_pos4, i, parent=my_pos)
                        n4.parent = rootNode
                        actions.append(n4)
        return actions

    #set UCT score to the list of children actions Nodes
    def setUCT(self, node):
        children = node.get_children()
        actions = children.keys()
        for i in range(len(actions)):
            valueA = actions[i].get_wins()/actions[i].get_visit()
            numA = actions[i].get_visit*()
            visitR = node.get_visit()
            uct = valueA + math.sqrt(2) * math.sqrt(math.log(visitR, np.e)/numA)
            children[actions[i]] = uct
        return children

    #find the best node to expand
    def findBestUCT(self, rootNode):
        #find all children of this current node
        rootChildren = rootNode.get_children()
        bestNode = None
        bestUCT = 0
        #for all children of this node, return the ones that either has the infinite UCT
        for key, value in rootChildren.items():
            if value == math.inf:
                return key
            #or the largest one
            elif value > bestUCT:
                bestNode = key
        return bestNode

    def select(self, rootNode):#start from the root node, select its children until leaf(uct can't decide)\
        while rootNode.getChildren():
            # descend a layer deeper
            rootNode = self.findBestUCT(self, rootNode)
        return rootNode

    def expand(self, leafNode, adv_pos, step, chess_board): #add all children to the leaf node
        AllChildren = self.getActions(self, leafNode.get_pos(), adv_pos, step, chess_board)
        children = dict()
        for i in range(len(AllChildren)):
            children[AllChildren[i]] = 0

    def updateNode(self, n, success):
        newVisit = n.get_visits() + 1
        n.set_visits(newVisit)
        if (success):
            newWin = n.get_wins() + 1
            n.set_wins(newWin)


    def backpropagation(self, lastExpand, success, numWins, totalV):
        while lastExpand.parent != None:
            self.updateNode(lastExpand, success)
            lastExpand = lastExpand.parent
            success = not success
        self.setUCT(lastExpand)

    def rollout(self, rootNode, adv_pos, step, chess_board):
        leafNode = self.select(rootNode)
        self.expand(leafNode, adv_pos, step, chess_board)
        numWins, totalV, success= self.m_simulate(chess_board, leafNode.get_pos(), adv_pos, step)
        self.backpropagation(leafNode, success, numWins, totalV)

def main():
    x = np.zeros((4, 4, 4), dtype=bool)
    x[0, :, 0] = True
    x[:, 0, 3] = True
    x[-1, :, 2] = True
    x[:, -1, 1] = True

    sa = agentTest()
    my_pos = (2, 2)
    adv_pos = (0,1)
    root = Node(my_pos, None, parent=None)
    #change root Node with UCT
    # chess_board = World()
    children = sa.getActions(root, adv_pos, 2, x)

    for i in range(len(children)):
        print(children[i].my_pos, children[i].dir)

if __name__ == "__main__":
    main()